version: "3.7"

services:
  wordpress:
    image: rsi1982 / pipelinesdotnetcoredocker
    ports:
      - "8087:5000"
    networks:
      - net
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: vip
networks:
- net
