version: "3.7"

services:
  pipelinesdotnetcoredocker:
    image: rsi1982/pipelinesdotnetcoredocker:15
    ports:
      - "8087:5000"
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: vip

